/* Сгенерировано re/mkdata.py */
#pragma once
#include <stdint.h>

extern const uint8_t d_cat[1440];
extern const uint8_t d_splat[180];
extern const uint8_t d_digits[160];
extern const uint16_t t_cat_walk[12];
extern const uint16_t t_cat_idle_a[8];
extern const uint16_t t_cat_idle_b[4];
extern const uint16_t t_cat_jump[6];
extern const uint16_t t_cat_jump_sz[6];
extern const uint16_t t_cat_tumble[8];
extern const uint16_t t_cat_tumble_sz[8];
extern const uint16_t t_room_cat_x[8];
extern const uint8_t t_room_cat_y[8];
extern const uint8_t d_dog[840];
extern const uint16_t t_dog_spr[8];
extern const uint8_t t_dog_appear[8];
extern const uint8_t t_dog_chase[8];
extern const uint16_t t_splat_div[16];
extern const uint16_t t_tune[67];
extern const uint16_t t_tune_fail[16];
extern const uint16_t t_tune_back[14];
extern const uint16_t t_bonus_snd[14];
extern const uint16_t t_wipe_snd[4];
extern const uint16_t t_rh_arp[8];
extern const uint16_t t_rh_tempo[4];
extern const uint8_t t_rh_bar[4];
extern const uint8_t t_rh_accmask[4];
extern const uint16_t t_rh_patofs[2];
extern const uint16_t t_rh_len[4];
extern const uint16_t t_rh_len2[2];
extern const uint8_t t_rh_acc[4];
extern const uint8_t t_rh_extra[4];
extern const uint8_t t_rh_pat[48];
extern const uint8_t t_bb_wake[32];
extern const uint8_t t_bb_spider[16];
extern const uint8_t t_room_matrix[12];
extern const uint8_t t_room_flat[5];
